name: Feature request
description: Suggest an improvement or new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement. Please describe your idea below.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? What's the current pain point?
      placeholder: "I find it frustrating when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've thought about?
    validations:
      required: false
