name: New tool proposal
description: Propose a new developer tool for DevFlow AI
title: "[Tool]: "
labels: ["new-tool"]
body:
  - type: markdown
    attributes:
      value: |
        Want to propose a new tool? Fill in the details so we can evaluate it before coding starts.

  - type: input
    id: name
    attributes:
      label: Tool name
      placeholder: "My awesome tool"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What problem does it solve?
      description: Describe the developer pain point this tool addresses.
    validations:
      required: true

  - type: textarea
    id: io
    attributes:
      label: Expected input / output
      description: What does the user provide, and what does the tool return?
      placeholder: |
        Input: A JSON string
        Output: Formatted and validated JSON with stats
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - analysis
        - review
        - calculation
        - visualization
        - management
        - generation
        - formatting
    validations:
      required: true

  - type: checkboxes
    id: constraints
    attributes:
      label: Constraints check
      options:
        - label: Can run 100% client-side (no server needed)
          required: true
        - label: Does not require external API keys
          required: true
        - label: Does not need heavy external libraries
          required: false
