import type { Tool } from "@/types/tools";

export const TOOLS_DATA: Tool[] = [
  {
    id: "1",
    name: "Prompt Analyzer",
    slug: "prompt-analyzer",
    description:
      "Analyze prompt quality, detect vulnerabilities, and optimize.",
    longDescription:
      "Prompt Analyzer is an advanced tool that evaluates the quality and security of your AI prompts. It detects potential prompt injection attacks, identifies areas for improvement, and provides a comprehensive score based on clarity, specificity, and safety. Perfect for developers working with LLM APIs who want to maximize prompt effectiveness.",
    icon: "FileSearch",
    category: "analysis",
    features: [
      "Quality scoring (1-10)",
      "Prompt injection detection",
      "Optimization suggestions",
      "Best practices comparison",
      "Real-time analysis",
    ],
    tags: ["AI", "Security", "Prompts", "Analysis"],
    rating: 4.8,
    usersCount: 1240,
    isFree: true,
    color: "from-blue-500 to-indigo-600",
  },
  {
    id: "2",
    name: "Code Review Assistant",
    slug: "code-review",
    description:
      "Automated code quality checks with AI-powered suggestions.",
    longDescription:
      "Code Review Assistant analyzes your code snippets for common issues, anti-patterns, and potential bugs. It provides detailed feedback on code quality, suggests refactoring opportunities, and calculates cyclomatic complexity. Supports TypeScript, JavaScript, Python, and more.",
    icon: "Code2",
    category: "review",
    features: [
      "Code smell detection",
      "Refactor suggestions",
      "Complexity analysis",
      "Multi-language support",
      "Inline annotations",
    ],
    tags: ["Code", "Quality", "Review", "AI"],
    rating: 4.7,
    usersCount: 980,
    isFree: true,
    color: "from-emerald-500 to-teal-600",
  },
  {
    id: "3",
    name: "API Cost Calculator",
    slug: "cost-calculator",
    description: "Compare costs across AI providers in real-time.",
    longDescription:
      "API Cost Calculator helps you understand and optimize your AI API spending. Input your usage patterns and see a detailed breakdown of costs across OpenAI, Anthropic, Google, and other providers. Get recommendations on the most cost-effective models for your specific use cases.",
    icon: "Calculator",
    category: "calculation",
    features: [
      "Multi-provider comparison",
      "Monthly cost projection",
      "Usage pattern analysis",
      "Cost optimization tips",
      "Export reports",
    ],
    tags: ["Costs", "APIs", "Optimization", "Finance"],
    rating: 4.9,
    usersCount: 1560,
    isFree: true,
    color: "from-amber-500 to-orange-600",
  },
  {
    id: "4",
    name: "Token Visualizer",
    slug: "token-visualizer",
    description: "Real-time token counting and visualization.",
    longDescription:
      "Token Visualizer shows exactly how AI models tokenize your text. See tokens highlighted in real-time as you type, understand token boundaries, and optimize your prompts for token efficiency. Supports GPT and Claude tokenization algorithms.",
    icon: "Eye",
    category: "visualization",
    features: [
      "Real-time tokenization",
      "Color-coded token types",
      "Token count estimation",
      "Cost estimation per token",
      "Multi-model support",
    ],
    tags: ["Tokens", "Visualization", "AI", "Analysis"],
    rating: 4.6,
    usersCount: 870,
    isFree: true,
    color: "from-purple-500 to-violet-600",
  },
  {
    id: "5",
    name: "Context Manager",
    slug: "context-manager",
    description: "Organize and optimize your LLM context windows.",
    longDescription:
      "Context Manager helps you build and optimize context windows for LLMs. Upload files, organize them by relevance, and see exactly how your context will look when sent to the API. Includes intelligent chunking and prioritization features.",
    icon: "FolderKanban",
    category: "management",
    features: [
      "Drag & drop organization",
      "Intelligent chunking",
      "Context preview",
      "Relevance scoring",
      "XML/JSON export",
    ],
    tags: ["Context", "LLM", "Organization", "AI"],
    rating: 4.5,
    usersCount: 650,
    isFree: true,
    color: "from-rose-500 to-pink-600",
  },
  {
    id: "6",
    name: "Regex Humanizer",
    slug: "regex-humanizer",
    description:
      "Explain regex in plain Spanish, generate patterns from descriptions.",
    longDescription:
      "Regex Humanizer makes regular expressions accessible. Paste any regex to get a detailed explanation in Spanish, or describe what you need and get the pattern generated for you. Includes a real-time tester with syntax highlighting and capture group visualization.",
    icon: "Regex",
    category: "analysis",
    features: [
      "Regex explanation in Spanish",
      "Pattern generation from text",
      "Real-time testing",
      "Syntax highlighting",
      "Capture group detection",
      "Common pattern presets",
    ],
    tags: ["Regex", "Analysis", "Generation", "Testing"],
    rating: 4.7,
    usersCount: 520,
    isFree: true,
    color: "from-cyan-500 to-blue-600",
  },
  {
    id: "7",
    name: "DTO-Matic",
    slug: "dto-matic",
    description:
      "Convert JSON to TypeScript interfaces, entities, and mappers instantly.",
    longDescription:
      "DTO-Matic transforms raw JSON API responses into production-ready TypeScript code. Generate clean interfaces, domain entities, and mapper functions following Clean Architecture principles. Supports date detection, Zod schemas, and multiple naming conventions. Save 20+ minutes of boilerplate per endpoint.",
    icon: "FileJson",
    category: "generation",
    features: [
      "JSON to TypeScript Interface",
      "Domain Entity generation",
      "Mapper functions (DTO ↔ Entity)",
      "Zod schema generation",
      "Date field detection",
      "Multiple naming conventions",
      "Clean Architecture ready",
    ],
    tags: ["TypeScript", "JSON", "Clean Architecture", "Code Generation"],
    rating: 4.9,
    usersCount: 890,
    isFree: true,
    color: "from-green-500 to-emerald-600",
  },
  {
    id: "8",
    name: "Cron Builder",
    slug: "cron-builder",
    description:
      "Visual cron expression builder with human-readable explanations.",
    longDescription:
      "Cron Builder makes scheduling easy. Build cron expressions visually without memorizing cryptic syntax. See human-readable explanations in Spanish, preview next execution times, and choose from common presets. Perfect for DevOps, backend developers, and anyone working with scheduled tasks.",
    icon: "Clock",
    category: "generation",
    features: [
      "Visual cron builder",
      "Human-readable explanations",
      "Next executions preview",
      "Common presets (hourly, daily, weekly)",
      "Real-time validation",
      "Copy to clipboard",
    ],
    tags: ["Cron", "Scheduling", "DevOps", "Automation"],
    rating: 4.8,
    usersCount: 720,
    isFree: true,
    color: "from-violet-500 to-purple-600",
  },
  {
    id: "9",
    name: "Tailwind Sorter",
    slug: "tailwind-sorter",
    description:
      "Sort and organize Tailwind CSS classes following best practices.",
    longDescription:
      "Tailwind Sorter brings order to your CSS classes. Paste any string of Tailwind classes and get them sorted by category (layout, spacing, typography, etc.), with duplicates removed and variants properly ordered. Choose between single-line, multi-line, or grouped output formats. Essential for maintaining consistent, readable Tailwind code.",
    icon: "Palette",
    category: "formatting",
    features: [
      "Sort by category (layout, spacing, typography...)",
      "Remove duplicate classes",
      "Variant ordering (sm → md → lg → xl)",
      "Multiple output formats",
      "Group visualization",
      "Copy sorted output",
      "Real-time preview",
    ],
    tags: ["Tailwind", "CSS", "Formatting", "Code Quality"],
    rating: 4.8,
    usersCount: 680,
    isFree: true,
    color: "from-sky-500 to-cyan-600",
  },
  {
    id: "10",
    name: "Variable Name Wizard",
    slug: "variable-name-wizard",
    description:
      "Generate perfect variable names and convert between naming conventions.",
    longDescription:
      "Variable Name Wizard helps you name things right the first time. Describe what you need and get contextual suggestions following best practices for your language. Convert existing names between camelCase, PascalCase, snake_case, kebab-case, and more. Includes abbreviation expansion/compression and type-specific recommendations.",
    icon: "Wand2",
    category: "generation",
    features: [
      "Generate names from descriptions",
      "Convert between 8 naming conventions",
      "Type-aware suggestions (hook, component, constant...)",
      "Abbreviation expansion/compression",
      "Automatic convention detection",
      "Copy any format instantly",
      "Language-specific recommendations",
    ],
    tags: ["Naming", "Variables", "Conventions", "Code Quality"],
    rating: 4.9,
    usersCount: 940,
    isFree: true,
    color: "from-fuchsia-500 to-pink-600",
  },
  {
    id: "11",
    name: "JSON Formatter",
    slug: "json-formatter",
    description:
      "Format, minify, validate JSON with path extraction and TypeScript generation.",
    longDescription:
      "JSON Formatter is your all-in-one JSON toolkit. Format with customizable indentation, minify for production, validate with detailed error messages, extract JSON paths, compare two JSON documents, and generate TypeScript interfaces. Includes real-time statistics showing keys, values, depth, and size metrics.",
    icon: "Braces",
    category: "formatting",
    features: [
      "Format with 2 or 4 space indentation",
      "Minify to single line",
      "Validate with error location",
      "Extract all JSON paths",
      "Compare two JSON documents",
      "Generate TypeScript interfaces",
      "Sort keys alphabetically",
      "Real-time size statistics",
    ],
    tags: ["JSON", "Formatting", "Validation", "TypeScript"],
    rating: 4.8,
    usersCount: 1120,
    isFree: true,
    color: "from-yellow-500 to-amber-600",
  },
  {
    id: "12",
    name: "Base64 Encoder/Decoder",
    slug: "base64",
    description:
      "Encode and decode Base64 with support for URL-safe variants and data URLs.",
    longDescription:
      "Base64 Encoder/Decoder handles all your Base64 encoding and decoding needs. Supports standard and URL-safe variants, handles Unicode text correctly, can generate and parse data URLs, and provides detailed statistics about input/output sizes. Perfect for working with APIs, embedding data, and debugging encoded content.",
    icon: "Binary",
    category: "formatting",
    features: [
      "Encode text to Base64",
      "Decode Base64 to text",
      "URL-safe variant support",
      "Data URL generation",
      "Unicode character support",
      "Size statistics",
      "Line break formatting",
      "Copy to clipboard",
    ],
    tags: ["Base64", "Encoding", "Decoding", "Data URL"],
    rating: 4.7,
    usersCount: 980,
    isFree: true,
    color: "from-indigo-500 to-blue-600",
  },
  {
    id: "13",
    name: "UUID Generator",
    slug: "uuid-generator",
    description:
      "Generate, validate, and parse UUIDs in all versions and formats.",
    longDescription:
      "UUID Generator creates universally unique identifiers in all major versions (v1, v4, v7, nil, max). Generate single or bulk UUIDs with multiple format options (standard, uppercase, no hyphens, braces, URN). Validate any UUID string and parse it to extract version, variant, timestamp, and node information. Essential for developers working with databases, APIs, and distributed systems.",
    icon: "Fingerprint",
    category: "generation",
    features: [
      "Generate UUID v1, v4, v7, nil, max",
      "Multiple formats (standard, uppercase, URN, braces)",
      "Bulk generation up to 1000",
      "Validate UUID strings",
      "Parse and extract UUID metadata",
      "Copy to clipboard",
    ],
    tags: ["UUID", "Generation", "Validation", "Identity"],
    rating: 4.8,
    usersCount: 1050,
    isFree: true,
    color: "from-teal-500 to-emerald-600",
  },
  {
    id: "14",
    name: "Git Commit Generator",
    slug: "git-commit-generator",
    description:
      "Generate conventional commit messages with type, scope, and validation.",
    longDescription:
      "Git Commit Generator helps you write perfect commit messages following the Conventional Commits specification. Select from 11 commit types with emoji indicators, add optional scope with smart suggestions, include body and footer sections, and get real-time validation. Parse existing commits to extract their components. Never write a malformed commit message again.",
    icon: "GitCommitHorizontal",
    category: "generation",
    features: [
      "11 commit types with emojis",
      "Smart scope suggestions",
      "72-char description counter",
      "Breaking change support",
      "Issue reference linking",
      "Parse existing commits",
      "Real-time validation",
    ],
    tags: ["Git", "Commits", "Conventional", "Generation"],
    rating: 4.9,
    usersCount: 870,
    isFree: true,
    color: "from-orange-500 to-red-600",
  },
  {
    id: "15",
    name: "HTTP Status Finder",
    slug: "http-status-finder",
    description:
      "Search and learn about HTTP status codes with examples and usage tips.",
    longDescription:
      "HTTP Status Finder is your comprehensive reference for HTTP status codes. Search by code number or keyword, filter by category (1xx-5xx), and get detailed information including description, when to use, and real-world examples. Features 55+ status codes with Spanish descriptions, color-coded categories, and quick access to the most common codes. Perfect for API developers and backend engineers.",
    icon: "Globe",
    category: "analysis",
    features: [
      "55+ HTTP status codes",
      "Search by code or keyword",
      "Filter by category (1xx-5xx)",
      "Detailed descriptions in Spanish",
      "When to use guidelines",
      "Real-world examples",
      "Color-coded categories",
    ],
    tags: ["HTTP", "Status Codes", "API", "Reference"],
    rating: 4.7,
    usersCount: 760,
    isFree: true,
    color: "from-cyan-500 to-blue-600",
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return TOOLS_DATA.find((tool) => tool.slug === slug);
}

export function getToolById(id: string): Tool | undefined {
  return TOOLS_DATA.find((tool) => tool.id === id);
}
